#[derive(Debug, Clone, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub enum Language {
    #[default]
    Pt,
    En,
}

pub struct T {
    pub app_title: &'static str,
    pub db_explorer: &'static str,
    pub load_db: &'static str,
    pub import_csv: &'static str,
    pub new_table: &'static str,
    pub compact_db: &'static str,
    pub search_placeholder: &'static str,
    pub tables: &'static str,
    pub theme: &'static str,
    pub rows_per_page: &'static str,
    pub no_file: &'static str,
    pub export: &'static str,
    pub new_record: &'static str,
    pub tab_data: &'static str,
    pub tab_schema: &'static str,
    pub tab_stats: &'static str,
    pub tab_sql: &'static str,
    pub search_data_placeholder: &'static str,
    pub search_btn: &'static str,
    pub clear_btn: &'static str,
    pub prev: &'static str,
    pub next: &'static str,
    pub page_of: &'static str,
    pub lines: &'static str,
    pub exec_sql: &'static str,
    pub tab_history: &'static str,
    pub tab_favorites: &'static str,
    pub footer_author: &'static str,
    pub edit: &'static str,
    pub delete: &'static str,
    pub rename: &'static str,
    pub warning: &'static str,
    pub error: &'static str,
    pub success: &'static str,
    pub confirm: &'static str,
    pub db_empty_warning: &'static str,
    pub restart_msg: &'static str,
    pub load_db_first: &'static str,
    pub enter_table_name: &'static str,
    pub vacuum_confirm: &'static str,
    pub vacuum_success: &'static str,
    pub confirm_delete_record: &'static str,
    pub confirm_delete_table: &'static str,
    pub record_updated: &'static str,
    pub record_inserted: &'static str,
    pub export_success: &'static str,
    pub no_data_export: &'static str,
    pub cancel: &'static str,
    pub save: &'static str,
    pub insert: &'static str,
    pub edit_values: &'static str,
    pub fill_values: &'static str,
    pub rename_table_prompt: &'static str,
    pub stats_table: &'static str,
    pub stats_filled: &'static str,
    pub stats_empty: &'static str,
    pub stats_top_values: &'static str,
    pub stats_no_data: &'static str,
    pub stats_error: &'static str,
    pub export_error: &'static str,
    pub file_loaded: &'static str,
    pub table_label: &'static str,
    pub select_csv_title: &'static str,
    pub table_name_title: &'static str,
    pub calculating_stats: &'static str,
    pub processing_column: &'static str,
    pub op_cancelled: &'static str,
    pub stats_unique: &'static str,
    pub stats_min: &'static str,
    pub stats_max: &'static str,
    pub stats_avg: &'static str,
    pub stats_saved: &'static str,
    pub create_table_title: &'static str,
    pub columns: &'static str,
    pub add_column: &'static str,
    pub foreign_keys: &'static str,
    pub add_fk: &'static str,
    pub col_name: &'static str,
    pub col_type: &'static str,
    pub pk: &'static str,
    pub nn: &'static str,
    pub ref_table: &'static str,
    pub ref_col: &'static str,
    pub ai: &'static str,
    pub remove: &'static str,
    pub erd_view: &'static str,
    pub erd_help: &'static str,
    pub all_columns: &'static str,
    pub filter_operator: &'static str,
    pub language_label: &'static str,
    pub export_stats: &'static str,
    pub open_sql_tab: &'static str,
    pub menu_file: &'static str,
    pub menu_table: &'static str,
    pub menu_settings: &'static str,
    pub menu_about: &'static str,
    pub about_title: &'static str,
    pub about_description: &'static str,
    pub about_org: &'static str,
    pub about_author: &'static str,
    pub about_version: &'static str,
    pub about_license: &'static str,
    pub about_copyright: &'static str,
    pub about_repository: &'static str,
    pub about_close: &'static str,
}

pub const PT: T = T {
    app_title: "SQLite Workbench",
    db_explorer: "Explorador DB",
    load_db: "Carregar .DB",
    import_csv: "Importar CSV",
    new_table: "Nova Tabela",
    compact_db: "Compactar DB",
    search_placeholder: "Pesquisar tabela...",
    tables: "Tabelas",
    theme: "Tema",
    rows_per_page: "Linhas por pág.:",
    no_file: "Nenhum ficheiro carregado.",
    export: "Exportar",
    new_record: "Novo Registo",
    tab_data: "Dados",
    tab_schema: "Esquema",
    tab_stats: "Estatísticas",
    tab_sql: "SQL",
    search_data_placeholder: "Pesquisar nos dados...",
    search_btn: "Pesquisar",
    clear_btn: "Limpar",
    prev: "Anterior",
    next: "Próxima",
    page_of: "de",
    lines: "linhas",
    exec_sql: "Executar",
    tab_history: "Histórico",
    tab_favorites: "Favoritos",
    footer_author: "Autor: Carlos Canuto Costa",
    edit: "Editar",
    delete: "Apagar",
    rename: "Renomear",
    warning: "Aviso",
    error: "Erro",
    success: "Sucesso",
    confirm: "Confirmar",
    db_empty_warning: "A base de dados está vazia. Pode importar um CSV.",
    restart_msg: "Reinicie a aplicação para aplicar o novo idioma.",
    load_db_first: "Carregue uma base de dados primeiro.",
    enter_table_name: "Nome da nova tabela:",
    vacuum_confirm: "Deseja compactar a base de dados (VACUUM)?",
    vacuum_success: "A base de dados foi compactada com sucesso.",
    confirm_delete_record: "Tem a certeza que quer apagar o registo com rowid {}?",
    confirm_delete_table: "Tem a certeza que quer apagar a tabela '{}'?",
    record_updated: "Registo atualizado.",
    record_inserted: "Registo inserido com sucesso.",
    export_success: "Exportado!",
    no_data_export: "Não há dados para exportar nesta aba.",
    cancel: "Cancelar",
    save: "Guardar",
    insert: "Inserir",
    edit_values: "Editar Valores",
    fill_values: "Preencher Valores",
    rename_table_prompt: "Novo nome para a tabela:",
    stats_table: "Tabela:",
    stats_filled: "preenchidos:",
    stats_empty: "vazios:",
    stats_top_values: "top valores:",
    stats_no_data: "sem dados",
    stats_error: "Erro ao gerar estatísticas:",
    export_error: "Erro ao exportar:",
    file_loaded: "Ficheiro:",
    table_label: "Tabela:",
    select_csv_title: "Selecionar Ficheiro CSV",
    table_name_title: "Nome da Tabela",
    calculating_stats: "A calcular estatísticas...",
    processing_column: "A processar coluna:",
    op_cancelled: "Operação cancelada.",
    stats_unique: "únicos:",
    stats_min: "min:",
    stats_max: "max:",
    stats_avg: "média:",
    stats_saved: "Estatísticas exportadas para:",
    create_table_title: "Criar Nova Tabela",
    columns: "Colunas",
    add_column: "+ Coluna",
    foreign_keys: "Chaves Estrangeiras",
    add_fk: "+ FK",
    col_name: "Nome",
    col_type: "Tipo",
    pk: "PK",
    nn: "NN",
    ref_table: "Tab. Ref.",
    ref_col: "Col. Ref.",
    ai: "AI",
    remove: "X",
    erd_view: "Diagrama ER",
    erd_help: "Arraste as tabelas para organizar o diagrama.",
    all_columns: "Todos",
    filter_operator: "Operador",
    language_label: "Idioma",
    export_stats: "Guardar JSON",
    open_sql_tab: "Abrir aba SQL",
    menu_file: "Ficheiro",
    menu_table: "Tabela",
    menu_settings: "Definições",
    menu_about: "Acerca de",
    about_title: "Acerca de SQLite Workbench",
    about_description: "Ferramenta de ambiente de trabalho para explorar e editar bases de dados SQLite.",
    about_org: "Organização",
    about_author: "Autor",
    about_version: "Versão",
    about_license: "Licença",
    about_copyright: "© 2025 NORMAXIS. Todos os direitos reservados.",
    about_repository: "Repositório",
    about_close: "Fechar",
};

pub const EN: T = T {
    app_title: "SQLite Workbench",
    db_explorer: "DB Explorer",
    load_db: "Load .DB",
    import_csv: "Import CSV",
    new_table: "New Table",
    compact_db: "Vacuum DB",
    search_placeholder: "Search table...",
    tables: "Tables",
    theme: "Theme",
    rows_per_page: "Rows per page:",
    no_file: "No file loaded.",
    export: "Export",
    new_record: "New Record",
    tab_data: "Data",
    tab_schema: "Schema",
    tab_stats: "Statistics",
    tab_sql: "SQL",
    search_data_placeholder: "Search data...",
    search_btn: "Search",
    clear_btn: "Clear",
    prev: "Previous",
    next: "Next",
    page_of: "of",
    lines: "lines",
    exec_sql: "Execute",
    tab_history: "History",
    tab_favorites: "Favorites",
    footer_author: "Author: Carlos Canuto Costa",
    edit: "Edit",
    delete: "Delete",
    rename: "Rename",
    warning: "Warning",
    error: "Error",
    success: "Success",
    confirm: "Confirm",
    db_empty_warning: "The database is empty. You can import a CSV.",
    restart_msg: "Restart the application to apply the new language.",
    load_db_first: "Please load a database first.",
    enter_table_name: "New table name:",
    vacuum_confirm: "Do you want to vacuum the database?",
    vacuum_success: "Database vacuumed successfully.",
    confirm_delete_record: "Are you sure you want to delete record with rowid {}?",
    confirm_delete_table: "Are you sure you want to delete table '{}'?",
    record_updated: "Record updated.",
    record_inserted: "Record inserted successfully.",
    export_success: "Exported!",
    no_data_export: "No data to export in this tab.",
    cancel: "Cancel",
    save: "Save",
    insert: "Insert",
    edit_values: "Edit Values",
    fill_values: "Fill in Values",
    rename_table_prompt: "New name for table:",
    stats_table: "Table:",
    stats_filled: "filled:",
    stats_empty: "empty:",
    stats_top_values: "top values:",
    stats_no_data: "no data",
    stats_error: "Error generating statistics:",
    export_error: "Error exporting:",
    file_loaded: "File:",
    table_label: "Table:",
    select_csv_title: "Select CSV File",
    table_name_title: "Table Name",
    calculating_stats: "Calculating statistics...",
    processing_column: "Processing column:",
    op_cancelled: "Operation cancelled.",
    stats_unique: "unique:",
    stats_min: "min:",
    stats_max: "max:",
    stats_avg: "avg:",
    stats_saved: "Statistics exported to:",
    create_table_title: "Create New Table",
    columns: "Columns",
    add_column: "+ Column",
    foreign_keys: "Foreign Keys",
    add_fk: "+ FK",
    col_name: "Name",
    col_type: "Type",
    pk: "PK",
    nn: "NN",
    ref_table: "Ref. Table",
    ref_col: "Ref. Col.",
    ai: "AI",
    remove: "X",
    erd_view: "ER Diagram",
    erd_help: "Drag tables to organize the diagram.",
    all_columns: "All",
    filter_operator: "Operator",
    language_label: "Language",
    export_stats: "Save JSON",
    open_sql_tab: "Open SQL tab",
    menu_file: "File",
    menu_table: "Table",
    menu_settings: "Settings",
    menu_about: "About",
    about_title: "About SQLite Workbench",
    about_description: "Desktop tool for exploring and editing SQLite databases.",
    about_org: "Organisation",
    about_author: "Author",
    about_version: "Version",
    about_license: "Licence",
    about_copyright: "© 2025 NORMAXIS. All rights reserved.",
    about_repository: "Repository",
    about_close: "Close",
};

pub fn get(lang: &Language) -> &'static T {
    match lang {
        Language::Pt => &PT,
        Language::En => &EN,
    }
}
